import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Providers from "@/lib/query-provider"
import Nav from "@/components/nav"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "px-24 max-w-4xl m-auto")}>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  )
}
